### ISSUE TITLE
feature updates or questions while writing the operator procedure

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#95] opened 2020-10-05 23:20 UTC
for reserve, spreadsheet format do we need:
- the column status (since it is always 'reserved')
- the PDS4 prefix in the product_specific_type
- submitter email (since it is in the command line arguments)

for reserve, how do we manage multuple authors ? 

Could we name related_resource lidvid ?

**Comment by jordanpadams** [comment] 2020-10-06 12:23
> for reserve, how do we manage multuple authors ?

do we care? this is just reserve, so its doesn't really matter, no?

> Could we name related_resource lidvid ?

Is this in the DOI metadata or something else?

**Comment by jordanpadams** [comment] 2021-04-01 04:16
closing this ticket since it is unknown what the issue is. will re-open if future node user's identify an issue.

**Closed by jordanpadams** 2021-04-01 04:16 UTC
Labels: enhancement, p.could-have
